=== s22a55m77/itprog/apps/php/menu.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!-- TODO @Jerome   -->
    <xsd:element name="Menu">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Category" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Dish" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="name" type="xs:string"/>
                    <xsd:element name="description" type="xs:string" minOccurs="0"/>
                    <xsd:element name="price" type="xs:nonNegativeInteger"/>
                    <xsd:element name="image" type="xs:string" minOccurs="0"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="name" type="xs:string"/>
            <xsd:attribute name="exist" type="xs:boolean"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== s22a55m77/itprog/apps/php/menu.xml
<?xml version="1.0" encoding="utf-8" ?>
<Menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="menu.xsd">
    <!-- Adding for existing category  -->
    <Category name="Mains" exist="true">
        <!-- min 0 max unbounded  -->
        <Dish>
            <name>Salad</name>
            <!--  optional -->
            <description>Salad Description</description>
            <!--  min 0 -->
            <price>100</price>
            <!--  optional -->
            <image>base64 string</image>
        </Dish>
    </Category>

    <!-- Adding for new category  -->
    <Category name="Mains" exist="false">
        <!-- min 0 max unbounded  -->
        <Dish>
            <name>Salad</name>
            <!--  min 0 -->
            <price>100</price>
            <!--  optional -->
            <image>base64 string</image>
        </Dish>
        <Dish>
            <name>Pizza</name>
            <!--  optional -->
            <description>Pizza Description</description>
            <!--  min 0 -->
            <price>150</price>
        </Dish>
    </Category>
</Menu>
