=== s22a55m77/itprog/apps/php/summary.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!-- TODO @Jerome   -->
    <xsd:element name="Summary">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="date" type="xs:date"/>
        <xsd:element name="amount" type="xs:nonNegativeInteger"/>
        <xsd:element name="discount" type="xs:nonNegativeInteger"/>
        <xsd:element name="Dishes">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="total" type="xs:nonNegativeInteger"/>
              <xsd:element name="Dish" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="name" type="xs:string"/>
                    <xsd:element name="sold" type="xs:nonNegativeInteger"/>
                  </xsd:sequence>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

</xsd:schema>

=== s22a55m77/itprog/apps/php/summary.xml
<?xml version="1.0" encoding="utf-8" ?>
<Summary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="summary.xsd">
    <!-- YYYY-MM-DD   -->
    <date>2023-07-18</date>
    <!-- non negative   -->
    <amount>1902</amount>
    <!-- non negative   -->
    <discount>180</discount>
    <!-- min 1 max 1   -->
    <Dishes>
        <!-- non negative   -->
        <total>12</total>
        <!-- min 0 max unbounded       -->
        <Dish>
            <name>Steak</name>
            <!-- non negative    -->
            <sold>6</sold>
        </Dish>
        <Dish>
            <name>Steamed Vegetables</name>
            <!-- non negative    -->
            <sold>8</sold>
        </Dish>
    </Dishes>
</Summary>
